#!/bin/bash



##Check VPN status
GET_VPN=$(nmcli con show | grep tun0 | cut -d ' ' -f1)

##Store status in STATUS
if [[ $GET_VPN == *"tun0"* ]]
then
    STATUS=
else
    STATUS=
fi


echo $STATUS
echo $STATUS



##Colors
if [[ "$STATUS" == "" ]]
then
    echo "#ebdbb2"
else
    echo "#ebdbb2"
fi
